"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var typography = {
    DM_Med_8_8: {
        fontSize: '8px',
        fontWeight: 500,
        lineHeight: '8px',
        letterSpacing: 0,
    },
    DM_Reg_10_10: {
        fontSize: '10px',
        fontWeight: 400,
        lineHeight: '10px',
        letterSpacing: 0,
    },
    DM_Med_10_12: {
        fontSize: '10px',
        fontWeight: 500,
        lineHeight: '12px',
        letterSpacing: 0,
    },
    DM_Reg_12_12_Chip: {
        fontSize: '12px',
        fontWeight: 400,
        lineHeight: '12px',
        letterSpacing: 0,
    },
    DM_Med_12_12_Chip: {
        fontSize: '12px',
        fontWeight: 500,
        lineHeight: '12px',
        letterSpacing: 0,
    },
    DM_Reg_12_16: {
        fontSize: '12px',
        fontWeight: 400,
        lineHeight: '16px',
        letterSpacing: 0,
    },
    DM_Med_12_16: {
        fontSize: '12px',
        fontWeight: 500,
        lineHeight: '16px',
        letterSpacing: 0,
    },
    DM_Reg_14_32_Table: {
        fontSize: '14px',
        fontWeight: 400,
        lineHeight: '32px',
        letterSpacing: 0,
    },
    DM_Med_14_20: {
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: '20px',
        letterSpacing: 0,
    },
    DM_Med_14_16: {
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: '16px',
        letterSpacing: 0,
    },
    DM_Reg_14_16: {
        fontSize: '14px',
        fontWeight: 400,
        lineHeight: '16px',
        letterSpacing: 0,
    },
    DM_Reg_14_24: {
        fontSize: '14px',
        fontWeight: 400,
        lineHeight: '24px',
        letterSpacing: 0,
    },
    DM_Med_16_16: {
        fontSize: '16px',
        fontWeight: 500,
        lineHeight: '16px',
        letterSpacing: 0,
    },
    DM_Btn_16_16_Med: {
        fontSize: '16px',
        fontWeight: 500,
        lineHeight: '16px',
        letterSpacing: 0,
    },
    DM_Reg_16_16_Chip: {
        fontSize: '16px',
        fontWeight: 400,
        lineHeight: '16px',
        letterSpacing: 0,
    },
    DM_Reg_16_20: {
        fontSize: '16px',
        fontWeight: 400,
        lineHeight: '20px',
        letterSpacing: 0,
    },
    DM_Reg_16_24: {
        fontSize: '16px',
        fontWeight: 400,
        lineHeight: '24px',
        letterSpacing: 0,
    },
    DM_Med_16_24: {
        fontSize: '16px',
        fontWeight: 500,
        lineHeight: '24px',
        letterSpacing: 0,
    },
    DM_Body_Reg_16: {
        fontSize: '16px',
        fontWeight: 400,
        lineHeight: '32px',
        letterSpacing: 0,
    },
    DM_Bold_16_24: {
        fontSize: '16px',
        fontWeight: 700,
        lineHeight: '24px',
        letterSpacing: 0,
    },
    DM_Reg_16_24_Italic: {
        fontSize: '16px',
        fontStyle: 'italic',
        fontWeight: 400,
        lineHeight: '24px',
        letterSpacing: 0,
    },
    DM_Med_18_24: {
        fontSize: '18px',
        fontWeight: 500,
        lineHeight: '24px',
        letterSpacing: 0,
    },
    DM_Med_20_24: {
        fontSize: '20px',
        fontWeight: 500,
        lineHeight: '24px',
        letterSpacing: 0,
    },
    DM_Med_24_24: {
        fontSize: '24px',
        fontWeight: 500,
        lineHeight: '24px',
        letterSpacing: 0,
    },
    DM_Med_32_32: {
        fontSize: '32px',
        fontWeight: 500,
        lineHeight: '32px',
        letterSpacing: 0,
    },
    DM_Reg_32_32: {
        fontSize: '32px',
        fontWeight: 400,
        lineHeight: '32px',
        letterSpacing: 0,
    },
    DM_Med_32_48: {
        fontSize: '32px',
        fontWeight: 500,
        lineHeight: '48px',
        letterSpacing: 0,
    },
    DM_Reg_40_56: {
        fontSize: '40px',
        fontWeight: 400,
        lineHeight: '56px',
        letterSpacing: 0,
    },
    DM_Bold_40_56: {
        fontSize: '40px',
        fontWeight: 700,
        lineHeight: '56px',
        letterSpacing: 0,
    },
    DM_Bold_14_24_UC: {
        fontSize: '14px',
        fontWeight: 700,
        lineHeight: '24px',
        letterSpacing: '0.03em',
        textTransform: 'uppercase',
    },
    DM_Med_14_24: {
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: '24px',
        letterSpacing: 0,
    },
};
exports.default = typography;
